export default {
  time:new Date().getTime(),
  verification:null,
  userName:null,
  awaitShow:false,
  // phoneNote:null,
  subscribe:1,
  recommendModDatas:null,
  recommendDatas:null,
  productDetailsPageData:null,
  listBanks:null,
  homeListBankCard:null,
  creditListBankCard:null,
  newListBankCard:null,
  ALLListBankCard:null,
  bankCardDetail:null,
  inviteurl:null,
  newsListFor:null,
  creditCardNews:null,
  newsList:null,
  detailForApp:null,
  orderListFor1:null,
  userrelated:null,
  rakeBackInfo:null,
  subordinateNum:null,
  erSubordinateNum:null,
  subordinateUserList:null,
  erSubordinateUserList:null,
  listScheduleFor:null,
  binBankCard:null,
  lastOrderInfo:null
}
